### ISSUE TITLE
crear Makefile

### ISSUE THREAD

**Issue by arma93ndo** [arma93ndo/practica7SO#1]
# Creacion de un Makefile con directivas para compilar proyecto.
1.- Compilar la rutina para el manejo de fallos de página. En este paso se generará un archivo .o que será encadenado al programa ejecutable.
```
cc –c pagefault.c
```

2.- Compilar el archivo donde están los procesos encadenándose a los archivos pagefault.o generado en el paso 1 y mmu.o.
```
cc –o procesos procesos.c mmu.o pagefault.o
```

**Comment by jorgeruvalcaba** [comment]
Compilado sin problema en Cloud9. Ver workspace.
